# Generated by Django 6.0.3 on 2026-03-19 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_is_all_day_alter_category_color_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="day",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
